#!/bin/bash
trap 'echo ""; echo "Proces potomny - otrzymałem sygnał SIGTSTP"; exit 1' 20
trap 'echo ""; echo "Proces potomny - otrzymałem sygnał SIGINT"; exit 1' 2

while [ 1 ]; do
  date
  sleep 1
done
